# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "devops-25b1-akg"
    encrypt = true
    key     = "EMA/DEV/aws/ec2-Frontend/terraform.tfstate"
    region  = "ap-south-1"
  }
}
